// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgstqflajwnucvqjfntt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnc3RxZmxhandudWN2cWpmbnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDQyMTgsImV4cCI6MjA2MjEyMDIxOH0.MU0hlYrByiuQnQ2XMD-IVWz3_jhdB6C0IpJYidxQN9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);